### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by BornWithGuns** [Hexer-7/Overwatch-Mercy-AI#2]
I don't use Instagram or TikTok and I'm new on here so idk how or if you can message people but I had few ideas. First one is that you could maybe do the same thing with life weaver almost where it heals right when his heal is fully charged. Idk about the second one if its possible cause of where the bar its located but whenever you shift/dash towards a person when the bar for mercy's jump gets in the threshold for max height it auto triggers. Maybe make it where that only happens if you hold shift maybe idk just ideas.  I know in the source I can go in the code and change the key binds and compile it for different ones but being able to change the key bind from left click or F2 would be nice but not necessary. Also this is probably too much but at it would be nice to also be able to control the thresh old at which it chooses to use dmg boost over heals. This is more of a personal one which I can probably just add myself but auto jump when holding left click while dmg/heal would be a nice option just cause I spam jump all the time and my finger gets tired lmao. I appreciate your work and keep it up thanks.

edit: also thought about anas anti grenade. would it be possible to make it swap to dmg when the person you are healing gets hit by her grenade since it puts that purple outline around the health bar? I think this would be a good thing to add if anything.

**Comment by Hexer-7** [comment]
I appreciate your interest in the project and your commitment to improving it. I will work on possible ideas and keep you updated on the progress of those that I manage to implement.

Regarding the idea of customizing the button, I will work on its implementation and make it part of an external config file. This file will be created upon the first run of the program and will include customization options for the heal and damage increase buttons, as well as buttons for code pause and sensitivity adjustment.

As for the sensitivity setting, I understand that it may be bothersome for some users, as it reflects the confidence level in artificial intelligence, making it complex and challenging to configure. However, I will include it in the config file as a precaution.

Concerning the code activation button, I can allow users to choose between the right and left mouse buttons, as they are typically easier for users compared to other buttons. I can also include various code settings in the config file, such as making Mercy's actions toggleable and other features. However, I realize that these settings might be complicated for users unfamiliar with programming, so I will consider simplifying them.

I will provide you with further updates once I figure out how to implement these great ideas. Thank you for your attention and support.

**Comment by Hexer-7** [comment]
Currently, the changes I will make to the code is include adding a feature to Mercy's weapon to swap to increase damage if the healed ally is affected by Ana's grenade.
I will dedicate a config file for advanced and default settings. 
Regarding Mercy's jump, I believe you need settings for Mercy super jump only, not artificial intelligence bot :)

**Comment by Hexer-7** [comment]
Hi, I have added some new features in v1.3. If you would like to try them on https://github.com/Hexer-7/Overwatch-Mercy-AI/releases.

I will try to make something good out of the idea of the character life weaver soon

**Comment by BornWithGuns** [comment]
Ill give it a try when I get home

**Comment by BornWithGuns** [comment]
I tried the new version and its crashing after I hit enter. Even crashes after restarting it after putting my heal, dmg, and resolution Using 6 heal, 7 dmg, 1080 for resolution

**Comment by Hexer-7** [comment]
yeah sorry it's because file config of 1080p resolution haven't <bomb_locations> like other resolutions, Thanks for telling me, i will fix that

**Comment by Hexer-7** [comment]
Done, now you can try download 1.3.0 again,
i made Life weaver but for now it's a beta version and will make it so sample not like mercy ai, so If you have any suggestions, I am all ears

**Comment by Hexer-7** [comment]
@BornWithGuns  you can try auto life weaver now on release https://github.com/Hexer-7/Overwatch-Auto-Life-Weaver/releases/tag/Auto-Life-Weaver1.0

**Comment by BornWithGuns** [comment]
Ive been using 1.3 and it works fine. I dont have LW unlocked on my other account yet so I cant test. I dont wanna run it on my main account just incase.

**Comment by Hexer-7** [comment]
you can try it on "no limits" or any mode except comp and qp.
btw i have tried it on main account, It is your right to be concerned about your account, but I want to emphasize that the program has no involvement in anything related to the game. 
It simply observes your screen and makes decisions based on what it sees.
I assure you, it is 99% safe.

**Comment by BornWithGuns** [comment]
ill try it later but OW got an update and LW is now 80 for heal so idk if that affects it or not

**Comment by Hexer-7** [comment]
Thanks for notifying me. I have updated it

**Comment by BornWithGuns** [comment]
just tested the LW one and its perfect

**Comment by BornWithGuns** [comment]
The only other one I could think of that could be useful is for sojourn. When you hit 100 charge while shooting it shoots the secondary fire. Also I guess you could do it with widow when aiming it shoots when it hits 100 charge but its probably not that great on her unless your a tracking god.
